name: Deployment # Workflow 이름
on:
  push: # release/*, demo, master Branch에 push 이벤트가 일어났을 때 실행
    branches:
      - release/*
      - demo
      - master

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on: ubuntu-latest # Job 가상환경 인스턴스
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2 # 현재 repository 소스 받아오기

      - name: Cache node modules # yarn.lock의 변경을 기준으로 node modules 캐싱
        uses: actions/cache@v2
        id: node-cache
        env:
          branch-name: ${GITHUB_REF#refs/heads/}
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ env.branch-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.branch-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Create env file
        uses: byj0101/action-test/.github/actions/env

      - name: Build
        run: ./node_modules/.bin/env-cmd -f .env yarn build
